import type { Metadata } from 'next';

import { AppConstants } from '@/app/app.constants';
import Providers from '@/src/components/layout/Providers/Providers';
import { FuturaDemiC } from '@/src/fonts/futura-font-familiy';

import './globals.scss';

const mainFont = FuturaDemiC;

export const metadata: Metadata = {
  title: {
    template: `%s | ${AppConstants.appName}`,
    default: AppConstants.appName,
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={mainFont.className}>
        <Providers>
          {/*<Header />*/}

          {children}

          {/*<Footer />*/}
        </Providers>
      </body>
    </html>
  );
}
